volumes:
  psql-data:
    external: true
  redis-data:
    external: true
  pgadmin4-data:
    external: true

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    ports:
      - 5050:80
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=redispw
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
