volumes:
  psql-data:
    external: true
  redis-data:
    external: true

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=redispw
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
